name: smartbin
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  fl_chart: ^0.69.2
  smooth_page_indicator: ^1.2.1
  mobile_scanner: ^3.5.7
  flutter_map: ^6.0.0 
  geolocator: ^13.0.3
  geolocator_android: 4.6.1
  latlong2: ^0.9.1
  url_launcher: ^6.2.4
  youtube_player_flutter: ^8.1.1
  provider: ^6.1.5
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

dependency_overrides:
  flutter_inappwebview: ^6.0.0-beta.23
